name: Manual Windows EXE Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; `
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install UPX using Chocolatey
        run: choco install upx

      - name: Build project
        run: cargo build --release

      - name: Compress Executable with UPX
        run: |
          upx --best --lzma target/release/internal-studio-patcher-reversed.exe

      - name: Upload Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: internal-studio-patcher-reversed
          path: target/release/internal-studio-patcher-reversed.exe
