name: Manual Windows EXE Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build project
        run: cargo build --release

      - name: Upload .exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: stagescan-exe
          path: target/release/stagescan.exe
